sno=int(input("enter student no:"))
name=input("enter student name:")
group=input("enter group:")
gender=input("enter gender:")
address=input("enter address:")
phn=input("enter phone:")
print(sno)
print(name)
print(group)
print(gender)
print(address)
print(phn)
