from tkinter import*
fb=Tk()
fb.title("Student form")
Label(fb,text="Enter Student regid:").grid(row=0)
Label(fb,text="Enter Student name:").grid(row=1)
Label(fb,text="Enter Father name:").grid(row=2)
Label(fb,text="Enter Group:").grid(row=3)
Label(fb,text="Enter Phone number:").grid(row=4)
Label(fb,text="Enter Email id:").grid(row=5)
Label(fb,text="Enter address:").grid(row=6)
Entry(fb).grid(row=0,column=1)
Entry(fb).grid(row=1,column=1)
Entry(fb).grid(row=2,column=1)
Entry(fb).grid(row=3,column=1)
Entry(fb).grid(row=4,column=1)
Entry(fb).grid(row=5,column=1)
Entry(fb).grid(row=6,column=1)
Button(fb,text="Submit").grid(row=7)
Button(fb,text="Cancel").grid(row=7,column=1)
mainloop()
